/* measured.js — GENERATED by tools/export_measured.py. Do not hand-edit.
 *
 * What each symbol/timeframe cell actually did, so the panel can show a cell
 * its own numbers instead of a binary badge. Generated rather than typed
 * because a figure in the UI that disagrees with the run that produced it is
 * worse than no figure at all.
 *
 * Re-run the exporter after any sweep:  python tools/export_measured.py
 *
 * VERDICTS
 *   validated     passed all four gates in sample AND out of sample
 *   failed_oos    passed in sample and then did not hold — the category an
 *                 in-sample-only report would have called a discovery
 *   no_edge       failed in sample
 *   undersampled  under the 200-trade floor: the question was not answerable,
 *                 which is NOT the same as a negative result
 *   pending_oos   passed in sample, no out-of-sample run yet
 *   unmeasured    no run covers this cell
 */

export const MEASURED = {
  "USDJPY.a|15m": {
    "is": {
      "avgR": -0.0699,
      "pass": false,
      "pct": 81.7,
      "pf": 0.864,
      "span": "2021-01-04..2026-08-21",
      "trades": 4233
    },
    "oos": null,
    "verdict": "no_edge"
  },
  "USDJPY.a|1d": {
    "is": {
      "avgR": 0.1532,
      "pass": false,
      "pct": 80.0,
      "pf": 1.261,
      "span": "2021-01-04..2026-08-21",
      "trades": 44
    },
    "oos": null,
    "verdict": "undersampled"
  },
  "USDJPY.a|1h": {
    "is": {
      "avgR": 0.0788,
      "pass": true,
      "pct": 96.7,
      "pf": 1.111,
      "span": "2021-01-04..2026-08-21",
      "trades": 1052
    },
    "oos": {
      "avgR": -0.058,
      "pass": false,
      "pct": 76.7,
      "pf": 0.896,
      "span": "2016-01-04..2020-12-31",
      "trades": 934
    },
    "verdict": "failed_oos"
  },
  "USDJPY.a|30m": {
    "is": {
      "avgR": 0.0093,
      "pass": false,
      "pct": 100.0,
      "pf": 1.002,
      "span": "2021-01-04..2026-08-27",
      "trades": 2225
    },
    "oos": null,
    "verdict": "no_edge"
  },
  "USDJPY.a|4h": {
    "is": {
      "avgR": -0.0186,
      "pass": false,
      "pct": 38.3,
      "pf": 0.952,
      "span": "2021-01-04..2026-08-21",
      "trades": 275
    },
    "oos": null,
    "verdict": "no_edge"
  },
  "USDJPY.a|5m": {
    "is": {
      "avgR": -0.3195,
      "pass": false,
      "pct": 0.0,
      "pf": 0.515,
      "span": "2021-01-04..2026-08-21",
      "trades": 996
    },
    "oos": null,
    "verdict": "no_edge"
  },
  "XAUUSD.a|15m": {
    "is": {
      "avgR": -0.0499,
      "pass": false,
      "pct": 76.7,
      "pf": 0.853,
      "span": "2021-01-04..2026-08-21",
      "trades": 4156
    },
    "oos": null,
    "verdict": "no_edge"
  },
  "XAUUSD.a|1d": {
    "is": {
      "avgR": 0.1649,
      "pass": false,
      "pct": 68.3,
      "pf": 1.282,
      "span": "2021-01-04..2026-08-21",
      "trades": 35
    },
    "oos": null,
    "verdict": "undersampled"
  },
  "XAUUSD.a|1h": {
    "is": {
      "avgR": -0.0025,
      "pass": false,
      "pct": 80.0,
      "pf": 0.977,
      "span": "2021-01-04..2026-08-21",
      "trades": 1039
    },
    "oos": null,
    "verdict": "no_edge"
  },
  "XAUUSD.a|30m": {
    "is": {
      "avgR": -0.0783,
      "pass": false,
      "pct": 8.3,
      "pf": 0.812,
      "span": "2021-01-04..2026-08-27",
      "trades": 2155
    },
    "oos": null,
    "verdict": "no_edge"
  },
  "XAUUSD.a|4h": {
    "is": {
      "avgR": 0.1897,
      "pass": true,
      "pct": 98.3,
      "pf": 1.327,
      "span": "2021-01-04..2026-08-26",
      "trades": 231
    },
    "oos": {
      "avgR": 0.2191,
      "pass": true,
      "pct": 96.7,
      "pf": 1.465,
      "span": "2016-01-04..2020-12-31",
      "trades": 207
    },
    "verdict": "validated"
  },
  "XAUUSD.a|5m": {
    "is": {
      "avgR": -0.2071,
      "pass": false,
      "pct": 0.0,
      "pf": 0.67,
      "span": "2021-01-04..2026-08-21",
      "trades": 1543
    },
    "oos": null,
    "verdict": "no_edge"
  }
};

export const VERDICT_TEXT = {
  validated: 'VALIDATED',
  failed_oos: 'DIED OUT OF SAMPLE',
  no_edge: 'NO EDGE FOUND',
  undersampled: 'TOO FEW TRADES',
  pending_oos: 'IN SAMPLE ONLY',
  unmeasured: 'NOT MEASURED',
};

/** The cell's record, or an unmeasured stub. `tf` is the bridge's vocabulary. */
export function measuredFor(symbol, tf) {
  return MEASURED[`${symbol}|${tf}`]
    || { verdict: 'unmeasured', is: null, oos: null };
}
