"""
The registry's `cells` and the generated `MEASURED` table must not drift apart.

TWO SOURCES ANSWER ONE QUESTION and they are maintained differently. A cell's
tradability is asserted by hand in js/chart/strategies.js (`status` + `cells`,
which js/ui/strategyreplay.js reads through `coversCell`) and generated from the
run archive into js/chart/measured.js (`verdict`, which the LIVE js/ui/rulepanel.js
reads through `measuredFor`). Nothing has been enforcing that they agree.

That matters because they feed different surfaces. The replay is a sandbox; the
rule panel sits beside the price you trade. If the exporter is re-run after a
sweep and the hand-written list is not updated, the live panel can call a cell
NO EDGE FOUND while the replay still presents it as covered by a validated
strategy -- or, worse, the reverse.

SCOPE. measured.js is generated by `tools/export_measured.py --strategy
donchian` and carries no strategy field, so it describes DONCHIAN ONLY. Its
cells are therefore cross-checked against the donchian entry alone; asserting
anything about ema_cross from this table would be reading one strategy's
numbers as another's. That limitation is the reason for `MEASURED_STRATEGY`
below rather than a loop over every registered rule.
"""
import json
import os
import shutil
import subprocess

import pytest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
NODE = shutil.which('node')

#: the strategy tools/export_measured.py defaults to, and therefore the only
#: one measured.js can speak for
MEASURED_STRATEGY = 'donchian'

READ = """
import { MEASURED } from './js/chart/measured.js';
import { STRATEGIES } from './js/chart/strategies.js';
console.log(JSON.stringify({
  measured: Object.fromEntries(Object.entries(MEASURED).map(([k, v]) => [k, v.verdict])),
  strategies: STRATEGIES.map((s) => ({ key: s.key, status: s.status, cells: s.cells || [] })),
}));
"""


@pytest.fixture(scope='module')
def js():
    if not NODE:
        pytest.skip('node not on PATH')
    res = subprocess.run([NODE, '--input-type=module', '-e', READ],
                         cwd=ROOT, capture_output=True, text=True, timeout=120)
    if res.returncode != 0:
        pytest.fail('node failed: %s' % res.stderr[-1500:])
    return json.loads(res.stdout)


def _cell_key(cell):
    """'XAUUSD.a 4h' as the registry writes it -> 'XAUUSD.a|4h' as MEASURED keys it."""
    symbol, tf = cell.rsplit(' ', 1)
    return '%s|%s' % (symbol, tf)


def _donchian(js):
    for s in js['strategies']:
        if s['key'] == MEASURED_STRATEGY:
            return s
    pytest.fail('%s missing from the registry' % MEASURED_STRATEGY)


def test_every_claimed_cell_has_been_measured(js):
    """A cell the registry claims must exist in the run archive at all."""
    s = _donchian(js)
    missing = [c for c in s['cells'] if _cell_key(c) not in js['measured']]
    assert not missing, (
        '%s claims cells with no measurement: %s -- re-run '
        'tools/export_measured.py or drop the claim' % (MEASURED_STRATEGY, missing))


def test_a_validated_strategy_claims_only_validated_cells(js):
    """
    The direction that would put an unvalidated cell in front of a trader as
    though it were covered.
    """
    s = _donchian(js)
    if s['status'] != 'validated':
        pytest.skip('%s is not marked validated' % MEASURED_STRATEGY)
    wrong = {c: js['measured'][_cell_key(c)] for c in s['cells']
             if js['measured'].get(_cell_key(c)) != 'validated'}
    assert not wrong, (
        'registry calls these cells covered by a VALIDATED strategy but the run '
        'archive disagrees: %s' % wrong)


def test_no_validated_cell_is_left_unclaimed(js):
    """
    The opposite drift: a sweep validates a cell, measured.js is regenerated,
    and the hand-written list is forgotten -- so the live panel says VALIDATED
    while the replay treats the cell as uncovered.
    """
    s = _donchian(js)
    claimed = {_cell_key(c) for c in s['cells']}
    validated = {k for k, v in js['measured'].items() if v == 'validated'}
    assert validated <= claimed, (
        'measured.js validates cells the registry does not list for %s: %s'
        % (MEASURED_STRATEGY, sorted(validated - claimed)))


def test_the_verdict_vocabularies_stay_in_step(js):
    """
    Both files carry their own vocabulary and the UI switches on both. A verdict
    the panel has no text for renders as a blank badge beside a price.
    """
    from_measured = set(js['measured'].values())
    known = {'validated', 'failed_oos', 'no_edge',
             'undersampled', 'pending_oos', 'unmeasured'}
    unknown = from_measured - known
    assert not unknown, 'measured.js emits verdicts VERDICT_TEXT cannot label: %s' % unknown
