/* recaudio.js — the soundtrack half of a replay recording.
 *
 * WHY IT IS ITS OWN FILE. Both replays already carry their own copy of the
 * MediaRecorder plumbing, and that duplication is tolerable because the two
 * compose different frames. The audio path composes nothing: it is the same
 * buffer, the same graph, the same codec negotiation and the same teardown
 * whichever panel asks for it. A third copy would be the one that drifts.
 *
 * IT IS NEVER AUDIBLE. The graph runs source -> gain -> MediaStreamDestination
 * and stops there; `ctx.destination`, which is the speakers, is not connected
 * to anything. So the track is rendered into the recording in real time and
 * the room stays silent -- you can record a fifteen-minute walk without
 * listening to a fifteen-second loop four hundred times, and a recording made
 * while you are on a call does not put music into it.
 *
 * THAT IS ALSO WHY IT IS NOT AN <audio> ELEMENT. An element's captureStream
 * gives the same track, but only while the element is actually playing, so the
 * sound would have to come out of the speakers to get into the file. Muting the
 * element does not help: in Chrome a muted element still yields a track, so the
 * file would have sound and the room would not -- but with no way to tell that
 * apart from a recording that captured silence until you play it back.
 *
 * THE TRACK. data/audio/countdown-fanfare.wav, an original piece generated by
 * tools/make_countdown.py -- see that file for what it is and why it was
 * written rather than sourced. Replace the file to change the music; the name
 * is fixed here because one soundtrack does not need a picker.
 */

/** The soundtrack, relative to the dev server's root. */
export const TRACK = 'countdown-fanfare.wav';
const URL_ = '/data/audio/' + TRACK;

/**
 * Codecs, in order of preference, for a recording WITH and WITHOUT sound.
 *
 * The two lists exist because asking for an audio codec you are not going to
 * feed produces a container with a silent, empty track in it -- which some
 * players show as a broken audio stream and others refuse outright. And going
 * the other way is worse: a video-only mime with an audio track attached to
 * the stream records the video and DROPS the sound, with no error, so the
 * first you know is when you play the file back.
 */
const MIME_SILENT = [
  'video/mp4;codecs=avc1.42E01E',
  'video/mp4',
  'video/webm;codecs=vp9',
  'video/webm',
];
const MIME_SOUND = [
  'video/mp4;codecs=avc1.42E01E,mp4a.40.2',
  'video/mp4',
  'video/webm;codecs=vp9,opus',
  'video/webm;codecs=vp8,opus',
  'video/webm',
];

/** The best container this browser will actually produce. Null if none. */
export function pickMime(withAudio) {
  const list = withAudio ? MIME_SOUND : MIME_SILENT;
  return list.find((t) => MediaRecorder.isTypeSupported(t)) || null;
}

/* Decoded once per page, not once per recording. The file is a couple of
   megabytes and decoding it is the only slow step here; a second recording
   should start on the click rather than after a round trip. */
let cached = null;

/**
 * Open the soundtrack as a silent, looping MediaStreamTrack.
 *
 * Returns `{ track, stop }`, or null when there is no soundtrack on disk or
 * the browser has no Web Audio -- both of which are ordinary, and both of
 * which mean the recording is made without sound rather than not made.
 *
 * CALL IT FROM THE CLICK that starts recording. An AudioContext created
 * outside a user gesture starts suspended and renders nothing, which would
 * produce a track carrying pure silence.
 *
 * `stop` is idempotent and must be called on every exit path, including
 * failure: an AudioContext left open holds an audio device awake.
 */
export async function openAudio({ volume = 0.8 } = {}) {
  const Ctx = window.AudioContext || window.webkitAudioContext;
  if (!Ctx) return null;

  let ctx = null;
  try {
    if (!cached) {
      const res = await fetch(URL_);
      if (!res.ok) return null;                 // no soundtrack installed
      cached = await res.arrayBuffer();
    }
    ctx = new Ctx();
    /* decodeAudioData detaches the buffer it is given, so it gets a copy --
       otherwise the cache is empty from the second recording onwards and the
       first one is the only one with sound. */
    const buf = await ctx.decodeAudioData(cached.slice(0));
    await ctx.resume();

    const dest = ctx.createMediaStreamDestination();
    const gain = ctx.createGain();
    gain.gain.value = volume;
    const src = ctx.createBufferSource();
    src.buffer = buf;
    src.loop = true;              // the walk is as long as you make it
    src.connect(gain);
    gain.connect(dest);
    /* deliberately NOT gain.connect(ctx.destination) -- see the file note */
    src.start();

    const track = dest.stream.getAudioTracks()[0] || null;
    if (!track) { ctx.close(); return null; }

    let stopped = false;
    return {
      name: TRACK,
      track,
      stop() {
        if (stopped) return;
        stopped = true;
        try { src.stop(); } catch { /* never started */ }
        try { track.stop(); } catch { /* already ended */ }
        ctx.close().catch(() => {});
      },
    };
  } catch {
    try { ctx?.close(); } catch { /* nothing to close */ }
    return null;
  }
}
