#!/usr/bin/env python
"""
export_measured.py — write what was MEASURED into a JS module the panel reads.

    python tools/export_measured.py

The chart used to carry a hand-written VALIDATED = {XAUUSD, 4h} and a red
NOT VALIDATED badge on everything else. That was true but nearly useless: it
told you a cell had not passed without telling you what it had actually done,
so every timeframe outside gold 4h looked identically forbidden -- USDJPY 30m,
which beat all sixty of its controls and made 0.009 R, sat under the same badge
as gold 5m, which lost 0.21 R and came last against every control it ran.

So the panel now shows each cell its own numbers. This file is what makes that
safe to do: it is GENERATED from runs/*.csv rather than typed, so the figures in
the UI cannot drift from the runs that produced them. Re-run it after any sweep.

VERDICTS, and why 'validated' is not simply 'passed the gates':

    validated     passed all four gates IN SAMPLE and OUT OF SAMPLE.
    failed_oos    passed in sample, then did not hold. The most important
                  category in the file: it is what an in-sample-only report
                  would have called a discovery.
    no_edge       failed in sample.
    undersampled  below the 200-trade floor. NOT a negative result -- the
                  question was not answerable, which is a different thing and
                  must not be displayed as a failure.
    unmeasured    no run covers this cell.

An in-sample pass with no out-of-sample run is NOT 'validated'. It is reported
as `pending_oos`, because that is exactly the state USDJPY 1h was in for the
twenty minutes before its OOS run came back negative.
"""
import argparse
import glob
import json
import os
import sys

import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'js', 'chart', 'measured.js')

#: (in-sample csv, out-of-sample csvs). Ordered: later files win, so a re-run
#: with a better cost model supersedes an older measurement of the same cell.
IS_GLOBS = ['runs/stage1_alltf_is.csv']
OOS_GLOBS = ['runs/stage1_alltf_oos_*.csv']

GATES = ('gate_sample', 'gate_profitable', 'gate_effect', 'gate_beats_control')


def truthy(v):
    return str(v).strip().lower() in ('true', '1', 'yes')


def rows(globs):
    out = {}
    for pattern in globs:
        for path in sorted(glob.glob(os.path.join(ROOT, pattern))):
            df = pd.read_csv(path)
            for r in df.itertuples():
                key = '%s|%s|%s' % (r.symbol, r.tf, r.strategy)
                out[key] = {
                    'trades': int(r.trades),
                    'avgR': round(float(r.avg_R), 4),
                    'pf': round(float(r.pf), 3),
                    'pct': round(float(r.percentile_vs_control), 1),
                    'span': str(r.span),
                    'gates': {g: truthy(getattr(r, g)) for g in GATES},
                    'pass': all(truthy(getattr(r, g)) for g in GATES),
                    'src': os.path.basename(path),
                }
    return out


def verdict(is_row, oos_row):
    if is_row is None:
        return 'unmeasured'
    if not is_row['gates']['gate_sample']:
        # the question was not answerable; do not call that a failure
        return 'undersampled'
    if not is_row['pass']:
        return 'no_edge'
    if oos_row is None:
        return 'pending_oos'
    return 'validated' if oos_row['pass'] else 'failed_oos'


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--strategy', default='donchian')
    args = ap.parse_args()

    is_all, oos_all = rows(IS_GLOBS), rows(OOS_GLOBS)
    cells = {}
    keys = {k for k in list(is_all) + list(oos_all)
            if k.rsplit('|', 1)[1] == args.strategy}
    for key in sorted(keys):
        symbol, tf, _ = key.split('|')
        i, o = is_all.get(key), oos_all.get(key)
        cells['%s|%s' % (symbol, tf)] = {
            'verdict': verdict(i, o),
            'is': i and {k: i[k] for k in ('trades', 'avgR', 'pf', 'pct',
                                           'span', 'pass')},
            'oos': o and {k: o[k] for k in ('trades', 'avgR', 'pf', 'pct',
                                            'span', 'pass')},
        }
    if not cells:
        sys.exit('no rows for strategy %r' % args.strategy)

    body = json.dumps(cells, indent=2, sort_keys=True)
    with open(OUT, 'w', encoding='utf-8', newline='') as fh:
        fh.write('''/* measured.js — GENERATED by tools/export_measured.py. Do not hand-edit.
 *
 * What each symbol/timeframe cell actually did, so the panel can show a cell
 * its own numbers instead of a binary badge. Generated rather than typed
 * because a figure in the UI that disagrees with the run that produced it is
 * worse than no figure at all.
 *
 * Re-run the exporter after any sweep:  python tools/export_measured.py
 *
 * VERDICTS
 *   validated     passed all four gates in sample AND out of sample
 *   failed_oos    passed in sample and then did not hold — the category an
 *                 in-sample-only report would have called a discovery
 *   no_edge       failed in sample
 *   undersampled  under the 200-trade floor: the question was not answerable,
 *                 which is NOT the same as a negative result
 *   pending_oos   passed in sample, no out-of-sample run yet
 *   unmeasured    no run covers this cell
 */

export const MEASURED = %s;

export const VERDICT_TEXT = {
  validated: 'VALIDATED',
  failed_oos: 'DIED OUT OF SAMPLE',
  no_edge: 'NO EDGE FOUND',
  undersampled: 'TOO FEW TRADES',
  pending_oos: 'IN SAMPLE ONLY',
  unmeasured: 'NOT MEASURED',
};

/** The cell's record, or an unmeasured stub. `tf` is the bridge's vocabulary. */
export function measuredFor(symbol, tf) {
  return MEASURED[`${symbol}|${tf}`]
    || { verdict: 'unmeasured', is: null, oos: null };
}
''' % body)

    print('wrote %s' % os.path.relpath(OUT, ROOT))
    for k in sorted(cells):
        c = cells[k]
        print('  %-16s %-13s IS %-9s OOS %s'
              % (k, c['verdict'],
                 '-' if not c['is'] else '%+.4f' % c['is']['avgR'],
                 '-' if not c['oos'] else '%+.4f' % c['oos']['avgR']))


if __name__ == '__main__':
    main()
